package com.ideepmind.joy.sdk;

public class DeviceReserve {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_reserve.c_id
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    private String id="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_reserve.c_device_id
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    private String deviceId="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_reserve.c_reserve_type
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    private String reserveType="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_reserve.c_reserve_period
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    private String reservePeriod="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_reserve.c_reserve_time
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    private String reserveTime="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_reserve.c_drink_type
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    private String drinkType="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_reserve.c_drink_name
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    private String drinkName="";
    
    private String command="";

    public String getCommand() {
		return command;
	}

	public void setCommand(String command) {
		this.command = command;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_reserve.c_id
     *
     * @return the value of t_device_reserve.c_id
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_reserve.c_id
     *
     * @param id the value for t_device_reserve.c_id
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_reserve.c_device_id
     *
     * @return the value of t_device_reserve.c_device_id
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_reserve.c_device_id
     *
     * @param deviceId the value for t_device_reserve.c_device_id
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_reserve.c_reserve_type
     *
     * @return the value of t_device_reserve.c_reserve_type
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    public String getReserveType() {
        return reserveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_reserve.c_reserve_type
     *
     * @param reserveType the value for t_device_reserve.c_reserve_type
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    public void setReserveType(String reserveType) {
        this.reserveType = reserveType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_reserve.c_reserve_period
     *
     * @return the value of t_device_reserve.c_reserve_period
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    public String getReservePeriod() {
        return reservePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_reserve.c_reserve_period
     *
     * @param reservePeriod the value for t_device_reserve.c_reserve_period
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    public void setReservePeriod(String reservePeriod) {
        this.reservePeriod = reservePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_reserve.c_reserve_time
     *
     * @return the value of t_device_reserve.c_reserve_time
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    public String getReserveTime() {
        return reserveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_reserve.c_reserve_time
     *
     * @param reserveTime the value for t_device_reserve.c_reserve_time
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    public void setReserveTime(String reserveTime) {
        this.reserveTime = reserveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_reserve.c_drink_type
     *
     * @return the value of t_device_reserve.c_drink_type
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    public String getDrinkType() {
        return drinkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_reserve.c_drink_type
     *
     * @param drinkType the value for t_device_reserve.c_drink_type
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    public void setDrinkType(String drinkType) {
        this.drinkType = drinkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_reserve.c_drink_name
     *
     * @return the value of t_device_reserve.c_drink_name
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    public String getDrinkName() {
        return drinkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_reserve.c_drink_name
     *
     * @param drinkName the value for t_device_reserve.c_drink_name
     *
     * @mbggenerated Tue Jan 03 14:23:36 CST 2017
     */
    public void setDrinkName(String drinkName) {
        this.drinkName = drinkName;
    }
}