package com.ideepmind.joy.sdk;

import java.util.Date;

public class LovedMusic {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_loved_music.c_id
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_loved_music.c_user_id
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_loved_music.c_song
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	private String song;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_loved_music.c_artist
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	private String artist;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_loved_music.c_duration
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	private String duration;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_loved_music.c_size
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	private String size;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_loved_music.c_url
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_loved_music.c_image_url
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	private String imageUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_loved_music.c_create_time
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_loved_music.c_sound
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	private String sound;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_loved_music.c_id
	 * @return  the value of t_loved_music.c_id
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_loved_music.c_id
	 * @param id  the value for t_loved_music.c_id
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_loved_music.c_user_id
	 * @return  the value of t_loved_music.c_user_id
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_loved_music.c_user_id
	 * @param userId  the value for t_loved_music.c_user_id
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_loved_music.c_song
	 * @return  the value of t_loved_music.c_song
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public String getSong() {
		return song;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_loved_music.c_song
	 * @param song  the value for t_loved_music.c_song
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public void setSong(String song) {
		this.song = song;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_loved_music.c_artist
	 * @return  the value of t_loved_music.c_artist
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public String getArtist() {
		return artist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_loved_music.c_artist
	 * @param artist  the value for t_loved_music.c_artist
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public void setArtist(String artist) {
		this.artist = artist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_loved_music.c_duration
	 * @return  the value of t_loved_music.c_duration
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public String getDuration() {
		return duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_loved_music.c_duration
	 * @param duration  the value for t_loved_music.c_duration
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public void setDuration(String duration) {
		this.duration = duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_loved_music.c_size
	 * @return  the value of t_loved_music.c_size
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public String getSize() {
		return size;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_loved_music.c_size
	 * @param size  the value for t_loved_music.c_size
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public void setSize(String size) {
		this.size = size;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_loved_music.c_url
	 * @return  the value of t_loved_music.c_url
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_loved_music.c_url
	 * @param url  the value for t_loved_music.c_url
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_loved_music.c_image_url
	 * @return  the value of t_loved_music.c_image_url
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public String getImageUrl() {
		return imageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_loved_music.c_image_url
	 * @param imageUrl  the value for t_loved_music.c_image_url
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_loved_music.c_create_time
	 * @return  the value of t_loved_music.c_create_time
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_loved_music.c_create_time
	 * @param createTime  the value for t_loved_music.c_create_time
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_loved_music.c_sound
	 * @return  the value of t_loved_music.c_sound
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public String getSound() {
		return sound;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_loved_music.c_sound
	 * @param sound  the value for t_loved_music.c_sound
	 * @mbggenerated  Mon Feb 13 15:48:14 CST 2017
	 */
	public void setSound(String sound) {
		this.sound = sound;
	}
}