package com.ideepmind.joy.sdk.cookbook;

import java.io.Serializable;

public class KindPeopleCook implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kind_people_cook.id
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kind_people_cook.type
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kind_people_cook.kind
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    private String kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kind_people_cook.kind_id
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    private Integer kindId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kind_people_cook.kind_info
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    private String kindInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kind_people_cook.good_info
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    private String goodInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kind_people_cook.bad_info
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    private String badInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kind_people_cook.id
     *
     * @return the value of kind_people_cook.id
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kind_people_cook.id
     *
     * @param id the value for kind_people_cook.id
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kind_people_cook.type
     *
     * @return the value of kind_people_cook.type
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kind_people_cook.type
     *
     * @param type the value for kind_people_cook.type
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kind_people_cook.kind
     *
     * @return the value of kind_people_cook.kind
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kind_people_cook.kind
     *
     * @param kind the value for kind_people_cook.kind
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    public void setKind(String kind) {
        this.kind = kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kind_people_cook.kind_id
     *
     * @return the value of kind_people_cook.kind_id
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    public Integer getKindId() {
        return kindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kind_people_cook.kind_id
     *
     * @param kindId the value for kind_people_cook.kind_id
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    public void setKindId(Integer kindId) {
        this.kindId = kindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kind_people_cook.kind_info
     *
     * @return the value of kind_people_cook.kind_info
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    public String getKindInfo() {
        return kindInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kind_people_cook.kind_info
     *
     * @param kindInfo the value for kind_people_cook.kind_info
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    public void setKindInfo(String kindInfo) {
        this.kindInfo = kindInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kind_people_cook.good_info
     *
     * @return the value of kind_people_cook.good_info
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    public String getGoodInfo() {
        return goodInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kind_people_cook.good_info
     *
     * @param goodInfo the value for kind_people_cook.good_info
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    public void setGoodInfo(String goodInfo) {
        this.goodInfo = goodInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kind_people_cook.bad_info
     *
     * @return the value of kind_people_cook.bad_info
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    public String getBadInfo() {
        return badInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kind_people_cook.bad_info
     *
     * @param badInfo the value for kind_people_cook.bad_info
     *
     * @mbggenerated Thu Aug 03 16:22:47 GMT+08:00 2017
     */
    public void setBadInfo(String badInfo) {
        this.badInfo = badInfo;
    }
}